name: 'Package Add-Ons'

on:
    push:
        branches:
            - main
jobs:
    release:
        name: Release packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.1.1

            - name: Set up Python
              uses: actions/setup-python@v5 
              with:
                python-version: '3.13'
            
            - name: Run Python script
              run: python package/package.py

            - name: Publish release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "addons/*.mcaddon,addons/*.mcpack,addons/*.zip"
                  bodyFile: "package/release.md"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: "download"
                  name: "Downloads"
                  replacesArtifacts: true
                  allowUpdates: true
                  removeArtifacts: true
