name: 'Package Add-Ons'

on:
    push:
        branches:
            - main

jobs:
    release:
        name: 📦 package
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.1.0
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.0
              env:
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: 📦 package
              run: npm publish --access public
              env:
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}